#
#server:
#  port: 8020
#logging:
#  level:
#    com:
#      microservice:
#        otpservice: debug
#spring:
#  application:
#    name: otpservice
#  redis:
#    host: localhost
#    port: 6379
#    timeout: 10s
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: otpservice
  config:
    url: http://localhost:8888
    import: configserver:http://localhost:8888
