#spring:
#  application:
#    name: emailservice
#  mail:
#    port: 2525
#    host: sandbox.smtp.mailtrap.io
#    username: e67e13d12b49b8
#    password: ed77f1f3e85cd3
#    properties:
#      smtp:
#        auth: true
#      mail:
#        smtp:
#          starttls:
#            enable: true
#server:
#  port: 8030
#logging:
#  level:
#    com:
#      service:
#        emailsender: debug
#  redis:
#    host: localhost
#    port: 6379
#    timeout: 10s
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: emailservice
  config:
    url: http://localhost:8888
    import: configserver:http://localhost:8888
